# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ac68a417947e13e34e960add40af2bc7aeb9a9232ed7ca573bf5cee9bc5593dfbb6b5c3fcd386d74428c627e3bc353e7042bcec99a870ac551ac68df9de636

test:
  secret_key_base: dcb284b34304fdad9a0eef62ddf983599ea8e2c0281ad2fae0eb89e6e1445d94775ea3b550d0db35b1ad78d5faf9abc8275c575204186c3584a812d2b56a40b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
